### ISSUE TITLE
frontend losing state

### ISSUE THREAD

**Issue by colinallen** [inpho/inphosemantics-old#2]
(Should this be an inphosite issue? -- anyway, here goes...)

Make some selections and load the data.
Hit 'Make selections' again and change value in number of results and hit enter while browser focus is still in the number box.

Results: 

In Safari: all the other values are cleared (= reset)

In Firefox, things sometimes things go wrong, but I can't figure out exactly how.  Sometimes the data is reloaded, but the next time you hit 'Make selections', all the values have been cleared; other times it loads a blank page.  (You may have to cycle through 'make selections' a few times to see this.)

**Comment by colinallen** [comment]
Values are also not being preserved when 'Export data' is selected, but I haven't opened a separate ticket on this because perhaps that part wasn't intended to be functional yet.

**Comment by rrose1** [comment]
Thank you for the bug report.

Since this is a front-end bug (interface state is handled either by the browser or the front-end server), would you repost it there? https://github.com/inpho/inphosemantics-frontend/issues?state=open

**Comment by colinallen** [comment]
Moving this bug to inphosemantics-frontend
